# 配置slq打印日志
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
    banner: false

# Logger Config
#logging:
#  level:
#    com.baomidou.mybatisplus.samples.quickstart: debug